export { authApi } from './auth.api';
export { usersApi } from './users.api';
export { assignmentsApi } from './assignments.api';
export { studyRoomsApi } from './studyRooms.api';
export { notificationsApi } from './notifications.api';
export { resourcesApi } from './resources.api';
export { semestersApi } from './semesters.api';
export { subjectsApi } from './subjects.api';
export { attendanceApi } from './attendance.api';
export { analyticsApi } from './analytics.api';
export { aiApi } from './ai.api';
export { notesApi } from './notes.api';
export { placementApi } from './placement.api';

export * from './client';
export * from './auth.api';
export * from './users.api';
export * from './onboarding.api';
export * from './semesters.api';
export * from './subjects.api';
export * from './attendance.api';
export * from './assignments.api';
export * from './notes.api';
export * from './resources.api';
export * from './analytics.api';
export * from './ai.api';
export * from './studyRooms.api';
export * from './notifications.api';
export * from './placement.api';
